### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by zischler** [samuelstalder/CO2-Calc#10]

**Comment by dandylife** [comment]
![Co2mmute_Logo_1](https://user-images.githubusercontent.com/43700703/133039257-c2643563-aa2a-4566-903d-105017d3f443.jpg)

**Comment by dandylife** [comment]
![co2mmute_logo_3](https://user-images.githubusercontent.com/43700703/133041291-966814bd-f71f-44cd-bd33-d222e6d1c4d8.png)

**Comment by dandylife** [comment]
![Co2mmute_Logo_4](https://user-images.githubusercontent.com/43700703/133043175-f16870f0-9f49-428d-b56c-9a8e6c46755c.png)

**Comment by dandylife** [comment]
![Co2mmute_Logo_5](https://user-images.githubusercontent.com/43700703/133044716-c1c2eb21-0d5c-4a55-badd-6ce5ce91b1da.jpg)

**Comment by dandylife** [comment]
![Co2mmute_Logo_6](https://user-images.githubusercontent.com/43700703/133044879-787a4377-532d-4817-9d9b-8532d05bd65b.jpg)

**Comment by dandylife** [comment]
![co2mmute_logo_10](https://user-images.githubusercontent.com/43700703/133051897-149f0150-d1e4-48c2-99a1-76b3af2d13e1.png)

**Comment by dandylife** [comment]
![co2mmute_logo_8](https://user-images.githubusercontent.com/43700703/133052612-0e749c32-959e-4a0e-a56a-b4583d5bf298.png)

**Comment by zischler** [comment]
implemented (co2 dark, rest white)
