### ISSUE TITLE
CO2 calculation formula

### ISSUE THREAD

**Issue by Omar8Richterswil** [samuelstalder/CO2-Calc#13]
depending on this document: https://www.epa.gov/sites/default/files/2016-03/documents/stationaryemissions_3_2016.pdf .
we used the tables to find the constant values such as **Emission Factors** and **heat value** for gasoline, diesel and gas.
according to this paper, we found we can calculate the emission of CO2 gas motor engines by using this formula:

CO2 emission = ef1 * distance * fuel usage  
ef1 =  Emission Factors * (heat value * 1000)
heat value multiplied by 1000 because the values in the table using gram (g) and we need to have with Kg.
be sure that the **distance is Kilometer** and **fuel usage is in Kilometer/ Liter.**
**heat value in kg CO2/ton.**
1- gas is 0.05444
2- Gasoline 8.78
3- diesel 11.09
**Emission Factors g CH4/ton**
1- gas is 0.00010
2- Gasoline 0.08
3- diesel 0.09

all resources calculating all gases that emission with CO2, its very small so we can neglected

**Comment by Omar8Richterswil** [comment]
this paper from EPA @samuelstalder @filliger 
It is an agency of the United States federal government whose mission is to protect human and environmental health. Headquartered in Washington, D.C., the EPA is responsible for creating standards and laws promoting the health of individuals and the environment.

**Comment by filliger** [comment]
Die Werte oben machen für mich nicht so sinn. Beispielsweise für Natural Gas (gas) sagst du der Heat Value ist 0.05444 CO2/ton. 
0.05444 ist aber der EmissionFactor für CO2 in kg CO2/scf (2). Heat Value ist das links daneben (1) 0.001026 mmBtu/scf.

Für z.b. Diesel (heavy gas oils) ist der EF (nicht heat value) 11.09, der Wert ist aber in kg CO2 / **Gallon** , nicht ton.

Ich denke es ist wichtig, dass diese Werte stimmen, deshalb sollten wir wahrscheinlich nochmal drüber und auch die Conversion zwischen den Einheiten berücksichtigen.
Falls ich etwas falsch verstanden habe, sorry.

![image](https://user-images.githubusercontent.com/57177747/133097327-14842f34-f36c-40a0-9c22-ae0c5237aff6.png)

**Comment by filliger** [comment]
Dies wären meiner Meinung nach die richtigen Werte aus der Tabelle 

Natural Gas:
HHV = 0.001026 mmBtu/scf
EF_CO2 = 0.05444 kg/scf

Motor Gasoline:
HHV = 0.125 mmBtu/gal
EF_CO2 = 8.78 kg/gal

Diesel (Heavy Gas Oils):
HHV = 0.148 mmBtu/gal
EF_CO2 = 11.09 kg/scf

scf steht für Standard Cubic Feet. Wir können die obigen Werte beibehalten und der Benutzer kann die Treibstoff-Menge in Liter angeben wenn wir im Hintergrund umrechnen. 
1 liter = 0.0353147 scf = 0.264172 gallon

**Comment by Omar8Richterswil** [comment]
Natural Gas:
HHV = 0.001026 mmBtu/scf
HHV in metric = 0.05444 kg/scf

Motor Gasoline:
HHV = 0.125 mmBtu/gal
HHV in metric = 8.78 kg/gal

Diesel (Heavy Gas Oils):
HHV = 0.148 mmBtu/gal
HVV in metric = 11.09 kg/scf

![image](https://user-images.githubusercontent.com/22518746/133103561-729f2b6d-4343-46b8-9f3c-4854cfb7ea2a.png)

**Comment by filliger** [comment]
Oben hast du EF1 benutzt. Es wäre beides möglich, aber der Report sagt auch, dass die Berechnung mit EF2 besser ist, und ist in unserem Fall auch einfacher. 

Also neue Berechnung:

_**CO2 = Fuel * HHV * EF2**_

**HHV** ist der Energiewert per Menge an Fuel und kommt aus Tabelle A-1:

_Natural Gas:  0.001026 mmBtu/scf
Gasoline: 0.125 mmBtu/gal
Diesel: HHV = 0.148 mmBtu/gal_

**EF2** ist der CO2-Ausstoss per Energiewert (HHV) und kommt aus Tabelle A-3:

_Natural Gas: 53.06 kg/mmBtu
Gasoline: 70.22 kg/mmBtu
Diesel: 74.92 kg/mmBtu_

Fuel bei HHV ist abundzu in scf, abundzu in gallons angegeben, wir wollen aber Liter. Deshalb müssen wir es umrechnen je nach Treibstoff:
_Fuel = (Verbrauch / 100) * Distanz)    
Verbrauch ist in [liter/100km]
Distanz ist in [km]
1L = 0.0353147 scf 
1L = 0.264172 gallon_


Beispiel Diesel-Auto mit 7.0l/100km Verbrauch und einem Arbeitsweg von 30km:
_Fuel = 7/100 * 30 = 2.1l_
Diesel HHV ist in gallons, deshalb umrechnen:
_Fuel = 2.1l * 0.264172 = 0.555 gal_
In Formel einsetzen mit Werten aus Tabellen:
_CO2 = 0.555 gal * 0.148 mmBtu/gal * 74.92 kg/mmBtu = **6.15kg CO2**_


Ich denke das sollte so stimmen und hoffe es ist verständlich für die Implementation..
