### ISSUE TITLE
Berechnungsgrundlage

### ISSUE THREAD

**Issue by samuelstalder** [samuelstalder/CO2-Calc#2]
Einfach und nachvollziehbare Formel für den CO2-Verbrauch einer Auto- oder Zugfahrt

**Comment by filliger** [comment]
Quellen für Zahlen die wir benutzen sollten rausgeschrieben werden für Doku

**Comment by Omar8Richterswil** [comment]
### according to https://www.engineeringtoolbox.com/fuels-densities-specific-volumes-d_166.html
1- The _density_ EN 590 **Diesel** ( for EU) is **820 (kg/m3)**
2- The _density_ of  **Gasoline** is **715 (kg/m3)**
3- The _density_ of **Natural gas**  is **0.7  (kg/m3)**
### according to https://www.epa.gov/sites/default/files/2015-07/documents/emission-factors_2014.pdf
1- _Heating Value_ for **Natural Gas** is **0.001026** mmBtu per scf
2-_Heating Value_ for  **Gasoline** is **0.135** mmBtu per scf
3-_Heating Value_ for  **Diesel** is **0.139** mmBtu per scf
### according to https://www.epa.gov/sites/default/files/2015-07/documents/emission-factors_2014.pdf
the unite changed to **liter** by multiplying the value from the source by 4.546
1-_Emission Factor_ for **Natural Gas** is **0.2477** kg CO2 per liter
2-_Emission Factor_ for  **Gasoline** is  **37.7772** kg CO2 per liter
3-_Emission Factor_ for  **Diesel** is  **46,3692** kg CO2 per liter

**Comment by Omar8Richterswil** [comment]
according to https://www.indexmundi.com/commodities/glossary/mmbtu
1 MMBtu = 28.263682 m3 of natural gas at defined temperature and pressure.
1- Heating Value for Natural Gas is 0.001026 mmBtu per scf * 28.263682 =
2-Heating Value for Gasoline is 0.135 mmBtu per scf * 28.263682 = 
3-Heating Value for Diesel is 0.139 mmBtu per scf *  28.263682 =

**Comment by Omar8Richterswil** [comment]
https://www.epa.gov/sites/default/files/2016-03/documents/stationaryemissions_3_2016.pdf
heat value in kg CO2/ton.
1-  gas is 0.05444
2- Gasoline 8.78
3- diesel 11.09

**Comment by Omar8Richterswil** [comment]
https://www.epa.gov/sites/default/files/2016-03/documents/stationaryemissions_3_2016.pdf
Emission Factors g CH4/ton
1- gas is 0.00010
2- Gasoline 0.08
3- diesel 0.09
