### ISSUE TITLE
Formular für Berechnung

### ISSUE THREAD

**Issue by samuelstalder** [samuelstalder/CO2-Calc#3]
Was muss man alles eingeben damit man die CO2-Ersparnisse berechnen kann. 

z.B
- Aktuelle Anzahl Homeoffice-Tage pro Woche: 0 - 5
- Zusätzliche Anzahl an Homeoffice-Tage: 1 - 5

Auto/Motorrad/Mofa
- Anzahl km pro Strecke
- Treibstoff
- Verbrauch Liter/100km

Velo/E-Bike
- Anzahl km pro Strecke

Zug/Tram/Bus
- Anzahl km pro Strecke

**Comment by Omar8Richterswil** [comment]
### For Cars & Motors
depending on this formula from https://www.ibm.com/docs/en/tririga/10.8?topic=calculations-carbon-footprint-calculation-formulas
### CO2 = ((Distance Traveled + Fuel Usage) * (Emission Factor * Heating Value) * Density)
**Emission Factor**, **Heating Value**, and **density** you can find in the issue _(Berechnungsgrundlage #2)._
these are all **constant**.
the user needs only to enter the **Distance Traveled** and his car **Fuel Usage**.

**Comment by Omar8Richterswil** [comment]
**CO2 in week** = CO2 in a day(using the distance between house and work) * number home offices days in a week
**CO2 in year** = CO2 in week * 52

**Comment by Omar8Richterswil** [comment]
according to https://de.wikipedia.org/wiki/Schweizerische_Bundesbahnen
all **trains and trams** are 100% of its network is electrified

**Comment by Omar8Richterswil** [comment]
for Bus, after searching in SBB website, the most common bus used by SBB is **Mercedes-Benz Citaro**
_https://en.wikipedia.org/wiki/Mercedes-Benz_Citaro_ .
for this bus, the engine is diesel ( you can get all diesel values from issue #2 ) and the Fuel Usage for this bus is **38.7 l/100 km** according to _https://media.daimler.com/marsMediaSite/en/instance/ko/Promise-kept-demonstrably-lower-fuel-consumption-with-Euro-VI-certified-Mercedes-Benz-Citaro-and-Setra-ComfortClass.xhtml?oid=9904236#:~:text=With%20a%20fuel%20consumption%20of,km%20or%208.5%20per%20cent._
so the user has to enter his **Distance Traveled** only

**Comment by Omar8Richterswil** [comment]
https://www.epa.gov/sites/default/files/2016-03/documents/stationaryemissions_3_2016.pdf
co2 = distance * Fuel Usage * Emission Factors * heat value * 1000
*1000 because in emission factor is Kg and heat value in g 
where Emission Factors and  heat value are constant values in issue number 2

**Comment by Omar8Richterswil** [comment]
the accuracy is not 100% because the used to calculate the  N2O which where not use
