### ISSUE TITLE
Zusätzlicher Inhalt auf der Webseite

### ISSUE THREAD

**Issue by samuelstalder** [samuelstalder/CO2-Calc#4]
Neben der Berechnung der CO2 Einsparungen sollen auch noch generelle Informationen zur verfügung gestellt werden

z.b
- Wissenschaftliche Grundlage der Berechnung
- Facts zur Einsparung von CO2
- CO2-Verbrauch von verschiedenen Autotypen
- Was wir nicht berücksichtigen bei unserer Berechnung. (Schwachstellen)
- Negative Folgen von Homeoffice im Bezug auf die Umwelt (z.b erhöhte Heizkosten, es werden mehr Bildschirme gekauft...)

**Comment by samuelstalder** [comment]
Man könnte auch den Inhalt des factsheet-home-office auf der Webseite einbinden.

**Comment by dandylife** [comment]
[co2mmute webtext.docx](https://github.com/samuelstalder/CO2-Calc/files/7156757/co2mmute.webtext.docx)
